
const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./routes/index.js']

const doc = {
    info: {
        version: "1.0.0",
        title: "Node Express Compass Uol",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "Utils",
            "description": "Utils endpoints"
        },
        {
            "name": "Product",
            "description": "Products endpoints"
        },
        {
            "name": "Auth",
            "description": "Authentication Endpoint"
        }
    ],
    securityDefinitions: {
        api_key: {
            type: "apiKey",
            name: "Authorization",
            in: "header"
        }
    },
    definitions: {
        User: {
            name: "Jhon Doe"
        },
        Product: {
            $name: "Sabonete",
            description: "Caixa de sabonete com 10 unidades",
            $price: 20,
            createdAt: "2022-12-22T12:18:06.844+0530",
            updatedAt: "2022-12-22T12:18:06.844+0530",
            createdBy: 1,
            updatedBy: 1,
        },
        addProduct: {
            $name: "Sabonete",
            description: "Caixa de sabonete com 10 unidades",
            $price: 20
        }
    }
}

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./app.js')
})